import type { Partner, Transaction, User } from './types';

export const partners: Partner[] = [
  {
    id: 'p001',
    companyName: 'Innovate Solutions',
    contactPerson: 'Alice Johnson',
    contactEmail: 'alice.j@innovate.com',
    status: 'Active',
    joinedDate: '2023-01-15',
    industry: 'Technology',
  },
  {
    id: 'p002',
    companyName: 'QuantumLeap Inc.',
    contactPerson: 'Bob Williams',
    contactEmail: 'bob.w@quantumleap.com',
    status: 'Active',
    joinedDate: '2022-11-20',
    industry: 'Finance',
  },
  {
    id: 'p003',
    companyName: 'Synergy Corp',
    contactPerson: 'Charlie Brown',
    contactEmail: 'charlie.b@synergy.com',
    status: 'Pending',
    joinedDate: '2023-05-10',
    industry: 'Healthcare',
  },
  {
    id: 'p004',
    companyName: 'Apex Logistics',
    contactPerson: 'Diana Prince',
    contactEmail: 'diana.p@apex.com',
    status: 'Inactive',
    joinedDate: '2021-08-01',
    industry: 'Logistics',
  },
  {
    id: 'p005',
    companyName: 'Starlight Media',
    contactPerson: 'Ethan Hunt',
    contactEmail: 'ethan.h@starlight.com',
    status: 'Active',
    joinedDate: '2023-03-22',
    industry: 'Media',
  },
];

export const transactions: Transaction[] = [
  {
    id: 't001',
    partnerId: 'p001',
    partnerName: 'Innovate Solutions',
    amount: 5000,
    status: 'Paid',
    date: '2023-06-01',
    type: 'Payment',
  },
  {
    id: 't002',
    partnerId: 'p002',
    partnerName: 'QuantumLeap Inc.',
    amount: 7500,
    status: 'Pending',
    date: '2023-06-15',
    type: 'Receipt',
  },
  {
    id: 't003',
    partnerId: 'p001',
    partnerName: 'Innovate Solutions',
    amount: 2500,
    status: 'Overdue',
    date: '2023-05-20',
    type: 'Payment',
  },
  {
    id: 't004',
    partnerId: 'p005',
    partnerName: 'Starlight Media',
    amount: 10000,
    status: 'Paid',
    date: '2023-06-05',
    type: 'Payment',
  },
  {
    id: 't005',
    partnerId: 'p002',
    partnerName: 'QuantumLeap Inc.',
    amount: 3000,
    status: 'Failed',
    date: '2023-06-10',
    type: 'Receipt',
  },
  {
    id: 't006',
    partnerId: 'p003',
    partnerName: 'Synergy Corp',
    amount: 1500,
    status: 'Pending',
    date: '2023-06-25',
    type: 'Payment',
  },
];

export const users: User[] = [
  {
    id: 'u001',
    name: 'Admin User',
    email: 'admin@paragon.com',
    role: 'Admin',
    avatarUrl: 'https://placehold.co/40x40.png',
  },
  {
    id: 'u002',
    name: 'Manager Mike',
    email: 'mike.m@paragon.com',
    role: 'Manager',
    avatarUrl: 'https://placehold.co/40x40.png',
  },
  {
    id: 'u003',
    name: 'Viewer Veronica',
    email: 'veronica.v@paragon.com',
    role: 'Viewer',
    avatarUrl: 'https://placehold.co/40x40.png',
  },
];
